/**
 * c-mastery-data.ts — 40-Day C Mastery Blueprint
 * Complete structured data for the C language learning path.
 */

export interface DayData {
  day: number;
  title: string;
  topics: string[];
  subtopics: string[];
  exercises: string[];
  goal: string;
  starterCode: string;
}

export interface PhaseData {
  id: number;
  name: string;
  tagline: string;
  color: string;
  gradient: string;
  icon: string;
  dayRange: [number, number];
  days: DayData[];
}

export const C_MASTERY_PHASES: PhaseData[] = [
  {
    id: 1,
    name: 'Brain Reset',
    tagline: 'Remove fear. Clean thinking. Understand how computer thinks.',
    color: '#22c55e',
    gradient: 'from-[#22c55e] to-[#16a34a]',
    icon: 'Brain',
    dayRange: [1, 5],
    days: [
      {
        day: 1, title: 'How Computer Thinks',
        topics: ['What is problem solving', 'How computer stores data', 'Binary idea (basic)', 'What is compiler', 'How C program runs internally', 'Structure of C program'],
        subtopics: ['Memory model (very basic)', 'What is instruction', 'What is logic', 'Human thinking vs computer thinking'],
        exercises: ['Write your first Hello World program', 'Print your name and age', 'Display a simple pattern using printf', 'Write a program that prints multiple lines'],
        goal: 'Student understands that programming = logical instructions.',
        starterCode: '#include <stdio.h>\n\nint main() {\n    // Your first C program!\n    // Try printing your name\n    printf("Hello, World!\\n");\n    return 0;\n}'
      },
      {
        day: 2, title: 'Data & Memory Control',
        topics: ['int, float, char data types', 'Variables & declaration', 'Memory addresses (intro)', 'ASCII values'],
        subtopics: ['Why data types matter', 'Overflow concept', 'Real-life memory example', 'sizeof operator'],
        exercises: ['Declare variables of each type and print them', 'Find ASCII value of a character', 'Swap two numbers', 'Calculate area of circle using float'],
        goal: 'Student understands how data is stored in memory.',
        starterCode: '#include <stdio.h>\n\nint main() {\n    int age = 20;\n    float height = 5.9;\n    char grade = \'A\';\n\n    printf("Age: %d\\n", age);\n    printf("Height: %.1f\\n", height);\n    printf("Grade: %c\\n", grade);\n\n    return 0;\n}'
      },
      {
        day: 3, title: 'Operators as Thinking Tools',
        topics: ['Arithmetic operators (+, -, *, /, %)', 'Logical operators (&&, ||, !)', 'Relational operators (<, >, ==, !=)', 'Operator precedence'],
        subtopics: ['Boolean thinking', 'Truth tables', 'Condition breakdown', 'Type casting in expressions'],
        exercises: ['Build a simple calculator', 'Check if a number is even or odd', 'Find the largest of two numbers', 'Convert temperature (C to F)'],
        goal: 'Convert real-life situations into conditions and expressions.',
        starterCode: '#include <stdio.h>\n\nint main() {\n    int a, b;\n    printf("Enter two numbers: ");\n    scanf("%d %d", &a, &b);\n\n    printf("Sum: %d\\n", a + b);\n    printf("Difference: %d\\n", a - b);\n    printf("Product: %d\\n", a * b);\n\n    return 0;\n}'
      },
      {
        day: 4, title: 'Decisions & Branching Mind',
        topics: ['if statement', 'if-else statement', 'Nested conditions'],
        subtopics: ['Decision tree thinking', 'Flowchart introduction', 'Multi-condition logic', 'Ternary operator'],
        exercises: ['Loan approval system', 'Age verification system', 'Password validation', 'Grade calculator (marks to grade)'],
        goal: 'Think in structured decision blocks.',
        starterCode: '#include <stdio.h>\n\nint main() {\n    int marks;\n    printf("Enter your marks: ");\n    scanf("%d", &marks);\n\n    if (marks >= 90) {\n        printf("Grade: A\\n");\n    } else if (marks >= 75) {\n        printf("Grade: B\\n");\n    } else if (marks >= 60) {\n        printf("Grade: C\\n");\n    } else {\n        printf("Grade: F\\n");\n    }\n\n    return 0;\n}'
      },
      {
        day: 5, title: 'Multi-path Thinking',
        topics: ['else-if ladder', 'switch statement', 'break & default'],
        subtopics: ['Menu-driven system design', 'Multiple decision structures', 'Fall-through concept', 'When to use switch vs if-else'],
        exercises: ['Menu-driven calculator', 'Day of week finder', 'Month days finder', 'Simple ATM menu system'],
        goal: 'Student starts thinking in structured logical blocks.',
        starterCode: '#include <stdio.h>\n\nint main() {\n    int choice;\n    printf("=== Simple Menu ===\\n");\n    printf("1. Addition\\n");\n    printf("2. Subtraction\\n");\n    printf("3. Exit\\n");\n    printf("Enter choice: ");\n    scanf("%d", &choice);\n\n    switch(choice) {\n        case 1: printf("You chose Addition\\n"); break;\n        case 2: printf("You chose Subtraction\\n"); break;\n        case 3: printf("Goodbye!\\n"); break;\n        default: printf("Invalid choice\\n");\n    }\n\n    return 0;\n}'
      },
    ],
  },
  {
    id: 2,
    name: 'Logic Muscle Building',
    tagline: 'Here brain becomes stronger. Build real logic power.',
    color: '#f59e0b',
    gradient: 'from-[#f59e0b] to-[#d97706]',
    icon: 'Dumbbell',
    dayRange: [6, 15],
    days: [
      { day: 6, title: 'Loop Thinking', topics: ['while loop', 'Loop condition analysis', 'Infinite loops & break'], subtopics: ['Repetition patterns in real life', 'Counter variables', 'Loop tracing', 'Sentinel-controlled loops'], exercises: ['Print 1 to N', 'Sum of N natural numbers', 'Reverse a number', 'Count digits in a number'], goal: 'Understand repetition as a fundamental logic tool.', starterCode: '#include <stdio.h>\n\nint main() {\n    int n, i = 1;\n    printf("Enter N: ");\n    scanf("%d", &n);\n\n    while (i <= n) {\n        printf("%d ", i);\n        i++;\n    }\n    printf("\\n");\n    return 0;\n}' },
      { day: 7, title: 'For Loop Deep Understanding', topics: ['for loop structure', 'Loop tracing exercises', 'Nested for intro'], subtopics: ['How loop runs in memory', 'Loop dry run practice', 'break & continue', 'Multiple loop variables'], exercises: ['Multiplication table', 'Factorial of N', 'Sum of digits', 'Power of a number without pow()'], goal: 'Master the for loop completely.', starterCode: '#include <stdio.h>\n\nint main() {\n    int n;\n    printf("Enter a number: ");\n    scanf("%d", &n);\n\n    long long fact = 1;\n    for (int i = 1; i <= n; i++) {\n        fact *= i;\n    }\n    printf("Factorial of %d = %lld\\n", n, fact);\n    return 0;\n}' },
      { day: 8, title: 'Pattern Analysis', topics: ['Nested loops deep dive', 'Star patterns', 'Number patterns'], subtopics: ['Row-column thinking', 'Space management', 'Pattern symmetry', 'Half & full pyramids'], exercises: ['Right triangle star pattern', 'Number pyramid', 'Inverted triangle', 'Diamond pattern'], goal: 'Improve spatial & structured thinking.', starterCode: '#include <stdio.h>\n\nint main() {\n    int n;\n    printf("Enter rows: ");\n    scanf("%d", &n);\n\n    for (int i = 1; i <= n; i++) {\n        for (int j = 1; j <= i; j++) {\n            printf("* ");\n        }\n        printf("\\n");\n    }\n    return 0;\n}' },
      { day: 9, title: 'Mathematical Logic Day', topics: ['Prime number check', 'Armstrong number', 'Palindrome number', 'Fibonacci series'], subtopics: ['Number theory thinking', 'Divisibility logic', 'Digit extraction', 'Mathematical sequences'], exercises: ['Check if number is prime', 'Find all primes up to N', 'Check Armstrong number', 'Check palindrome number'], goal: 'Number theory thinking mastery.', starterCode: '#include <stdio.h>\n\nint main() {\n    int n, isPrime = 1;\n    printf("Enter a number: ");\n    scanf("%d", &n);\n\n    if (n <= 1) isPrime = 0;\n    for (int i = 2; i * i <= n; i++) {\n        if (n % i == 0) { isPrime = 0; break; }\n    }\n\n    printf("%d is %s\\n", n, isPrime ? "Prime" : "Not Prime");\n    return 0;\n}' },
      { day: 10, title: 'Problem Decomposition', topics: ['Break big problems into steps', 'Writing algorithm before coding', 'Pseudocode practice'], subtopics: ['Step-by-step thinking', 'Input-Process-Output model', 'Edge case awareness', 'Testing your logic'], exercises: ['Design algorithm for ATM withdrawal', 'Write pseudocode for sorting 3 numbers', 'Break down a billing system', 'Design login validation flow'], goal: 'Student learns to think before typing.', starterCode: '#include <stdio.h>\n\n// Problem: Simple billing system\n// Step 1: Take item prices\n// Step 2: Calculate subtotal\n// Step 3: Apply tax (18%)\n// Step 4: Display final bill\n\nint main() {\n    float price1, price2, subtotal, tax, total;\n\n    printf("Enter price of item 1: ");\n    scanf("%f", &price1);\n    printf("Enter price of item 2: ");\n    scanf("%f", &price2);\n\n    subtotal = price1 + price2;\n    tax = subtotal * 0.18;\n    total = subtotal + tax;\n\n    printf("\\n--- BILL ---\\n");\n    printf("Subtotal: %.2f\\n", subtotal);\n    printf("Tax (18%%): %.2f\\n", tax);\n    printf("Total: %.2f\\n", total);\n    return 0;\n}' },
      { day: 11, title: 'Functions as Thinking Blocks', topics: ['What is modular programming', 'Function declaration & definition', 'Why functions matter'], subtopics: ['Scope of variables', 'Stack memory intro', 'Local vs global variables', 'Function prototypes'], exercises: ['Create add, subtract, multiply functions', 'Function to check even/odd', 'Function to find max of two numbers', 'Function to calculate power'], goal: 'Think in reusable modules.', starterCode: '#include <stdio.h>\n\nint add(int a, int b) {\n    return a + b;\n}\n\nint isEven(int n) {\n    return n % 2 == 0;\n}\n\nint main() {\n    printf("5 + 3 = %d\\n", add(5, 3));\n    printf("4 is %s\\n", isEven(4) ? "Even" : "Odd");\n    return 0;\n}' },
      { day: 12, title: 'Deep Function Control', topics: ['Parameters & arguments', 'Return values', 'Call stack visualization'], subtopics: ['Pass by value', 'Multiple return using pointers (intro)', 'Void functions', 'Function overloading concept'], exercises: ['Function to find GCD', 'Function to check prime', 'Calculator using functions', 'Swap using function (pass by value demo)'], goal: 'Full mastery of function mechanics.', starterCode: '#include <stdio.h>\n\nint gcd(int a, int b) {\n    while (b != 0) {\n        int temp = b;\n        b = a % b;\n        a = temp;\n    }\n    return a;\n}\n\nint main() {\n    int a, b;\n    printf("Enter two numbers: ");\n    scanf("%d %d", &a, &b);\n    printf("GCD of %d and %d = %d\\n", a, b, gcd(a, b));\n    return 0;\n}' },
      { day: 13, title: 'Recursion & Brain Expansion', topics: ['Recursion concept', 'Base case & recursive case', 'Recursive thinking patterns'], subtopics: ['Stack visualization in recursion', 'Recursive vs iterative', 'When to use recursion', 'Stack overflow awareness'], exercises: ['Factorial using recursion', 'Fibonacci using recursion', 'Sum of digits recursively', 'Power function recursively'], goal: 'Understand self-reference logic.', starterCode: '#include <stdio.h>\n\nint factorial(int n) {\n    if (n <= 1) return 1;  // Base case\n    return n * factorial(n - 1);  // Recursive case\n}\n\nint fibonacci(int n) {\n    if (n <= 1) return n;\n    return fibonacci(n-1) + fibonacci(n-2);\n}\n\nint main() {\n    printf("5! = %d\\n", factorial(5));\n    printf("Fib(7) = %d\\n", fibonacci(7));\n    return 0;\n}' },
      { day: 14, title: 'Structured Multi-step Logic', topics: ['Multi-function problem solving', 'Designing small systems', 'Code organization'], subtopics: ['Header comments', 'Function grouping', 'Main as orchestrator', 'Input validation'], exercises: ['Build a billing system with functions', 'Student grade system', 'Mini calculator with menu', 'Number analysis tool (prime, palindrome, etc.)'], goal: 'Build complete small programs using functions.', starterCode: '#include <stdio.h>\n\nvoid displayMenu() {\n    printf("\\n=== Number Analyzer ===\\n");\n    printf("1. Check Prime\\n");\n    printf("2. Check Palindrome\\n");\n    printf("3. Factorial\\n");\n    printf("4. Exit\\n");\n}\n\nint isPrime(int n) {\n    if (n <= 1) return 0;\n    for (int i = 2; i*i <= n; i++)\n        if (n % i == 0) return 0;\n    return 1;\n}\n\nint main() {\n    int choice, num;\n    do {\n        displayMenu();\n        printf("Choice: ");\n        scanf("%d", &choice);\n        if (choice >= 1 && choice <= 3) {\n            printf("Enter number: ");\n            scanf("%d", &num);\n        }\n        switch(choice) {\n            case 1: printf("%d is %sPrime\\n", num, isPrime(num)?"":"Not "); break;\n            case 4: printf("Bye!\\n"); break;\n            default: printf("Try again\\n");\n        }\n    } while(choice != 4);\n    return 0;\n}' },
      { day: 15, title: 'Mini Logic Exam', topics: ['10 mixed difficulty problems', 'Timed practice session', 'Self-assessment'], subtopics: ['Logic clarity check', 'Speed coding practice', 'Error debugging', 'Code optimization basics'], exercises: ['Reverse a number', 'Find LCM of two numbers', 'Print Fibonacci up to N', 'Count vowels in a string', 'Find second largest in 3 numbers', 'Digital root of a number', 'Sum of series 1+1/2+1/3...', 'Check perfect number', 'Print multiplication table', 'Simple pattern challenge'], goal: 'Self-assessment of logic mastery so far.', starterCode: '#include <stdio.h>\n\n// Mini Logic Exam - Day 15\n// Solve as many problems as you can!\n\n// Problem 1: Reverse a number\nint reverseNum(int n) {\n    int rev = 0;\n    while (n > 0) {\n        rev = rev * 10 + n % 10;\n        n /= 10;\n    }\n    return rev;\n}\n\nint main() {\n    int num;\n    printf("Enter a number: ");\n    scanf("%d", &num);\n    printf("Reversed: %d\\n", reverseNum(num));\n    return 0;\n}' },
    ],
  },
  {
    id: 3,
    name: 'Structured Thinking',
    tagline: 'Now we build real depth with arrays, strings, and structures.',
    color: '#3b82f6',
    gradient: 'from-[#3b82f6] to-[#2563eb]',
    icon: 'Layers',
    dayRange: [16, 25],
    days: [
      { day: 16, title: 'Arrays as Data Collections', topics: ['1D array declaration', 'Array initialization', 'Memory mapping of arrays'], subtopics: ['Index-based access', 'Array bounds', 'Array traversal', 'sizeof with arrays'], exercises: ['Input N elements and display', 'Find sum and average', 'Find max and min element', 'Count occurrences of an element'], goal: 'Understand collections of data.', starterCode: '#include <stdio.h>\n\nint main() {\n    int arr[100], n;\n    printf("How many elements? ");\n    scanf("%d", &n);\n\n    printf("Enter %d elements:\\n", n);\n    for (int i = 0; i < n; i++)\n        scanf("%d", &arr[i]);\n\n    int sum = 0;\n    for (int i = 0; i < n; i++)\n        sum += arr[i];\n\n    printf("Sum = %d, Average = %.2f\\n", sum, (float)sum/n);\n    return 0;\n}' },
      { day: 17, title: 'Array Logic Deep Dive', topics: ['Linear search', 'Bubble sort', 'Selection sort'], subtopics: ['Searching algorithms', 'Sorting algorithms', 'Time complexity intro', 'Array manipulation'], exercises: ['Linear search implementation', 'Bubble sort implementation', 'Find second largest element', 'Remove duplicates from array'], goal: 'Master array operations.', starterCode: '#include <stdio.h>\n\nvoid bubbleSort(int arr[], int n) {\n    for (int i = 0; i < n-1; i++)\n        for (int j = 0; j < n-i-1; j++)\n            if (arr[j] > arr[j+1]) {\n                int temp = arr[j];\n                arr[j] = arr[j+1];\n                arr[j+1] = temp;\n            }\n}\n\nint main() {\n    int arr[] = {64, 25, 12, 22, 11};\n    int n = 5;\n    bubbleSort(arr, n);\n    printf("Sorted: ");\n    for (int i = 0; i < n; i++)\n        printf("%d ", arr[i]);\n    printf("\\n");\n    return 0;\n}' },
      { day: 18, title: 'Optimization Thinking', topics: ['Reduce unnecessary loops', 'Better logic writing', 'Binary search'], subtopics: ['Early termination', 'Flag variables', 'Efficient algorithms', 'Comparing approaches'], exercises: ['Binary search implementation', 'Optimize bubble sort (flag)', 'Find missing number in 1-N', 'Two sum problem (brute force)'], goal: 'Write efficient code.', starterCode: '#include <stdio.h>\n\nint binarySearch(int arr[], int n, int target) {\n    int low = 0, high = n - 1;\n    while (low <= high) {\n        int mid = (low + high) / 2;\n        if (arr[mid] == target) return mid;\n        else if (arr[mid] < target) low = mid + 1;\n        else high = mid - 1;\n    }\n    return -1;\n}\n\nint main() {\n    int arr[] = {2, 5, 8, 12, 16, 23, 38, 56, 72, 91};\n    int target = 23;\n    int result = binarySearch(arr, 10, target);\n    printf("%d found at index %d\\n", target, result);\n    return 0;\n}' },
      { day: 19, title: '2D Arrays & Matrix Logic', topics: ['2D array declaration', 'Matrix input/output', 'Matrix operations'], subtopics: ['Row-column thinking', 'Real-life grid applications', 'Diagonal elements', 'Matrix transpose'], exercises: ['Matrix addition', 'Matrix multiplication', 'Find diagonal sum', 'Transpose a matrix'], goal: 'Think in grids and matrices.', starterCode: '#include <stdio.h>\n\nint main() {\n    int mat[3][3] = {{1,2,3},{4,5,6},{7,8,9}};\n    \n    printf("Matrix:\\n");\n    for (int i = 0; i < 3; i++) {\n        for (int j = 0; j < 3; j++)\n            printf("%d ", mat[i][j]);\n        printf("\\n");\n    }\n    \n    int diagSum = 0;\n    for (int i = 0; i < 3; i++)\n        diagSum += mat[i][i];\n    printf("Diagonal sum: %d\\n", diagSum);\n    return 0;\n}' },
      { day: 20, title: 'Strings', topics: ['String declaration', 'String input/output', 'String functions (strlen, strcpy, strcat)'], subtopics: ['Null terminator concept', 'Character arrays vs strings', 'gets vs fgets', 'String manipulation'], exercises: ['Find string length manually', 'Reverse a string', 'Check if string is palindrome', 'Count vowels and consonants'], goal: 'Master text manipulation.', starterCode: '#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char str[100];\n    printf("Enter a string: ");\n    fgets(str, 100, stdin);\n    str[strcspn(str, "\\n")] = 0;\n\n    int len = strlen(str);\n    printf("Length: %d\\n", len);\n\n    // Reverse\n    printf("Reversed: ");\n    for (int i = len-1; i >= 0; i--)\n        printf("%c", str[i]);\n    printf("\\n");\n    return 0;\n}' },
      { day: 21, title: 'Advanced String Logic', topics: ['Pattern matching', 'Token logic (strtok)', 'Word parsing'], subtopics: ['Substring search', 'String comparison', 'Case conversion', 'Word count'], exercises: ['Count words in a sentence', 'Convert string to uppercase', 'Find substring in string', 'Remove spaces from string'], goal: 'Advanced text processing skills.', starterCode: '#include <stdio.h>\n#include <string.h>\n#include <ctype.h>\n\nint countWords(char str[]) {\n    int count = 0, inWord = 0;\n    for (int i = 0; str[i]; i++) {\n        if (isspace(str[i])) inWord = 0;\n        else if (!inWord) { inWord = 1; count++; }\n    }\n    return count;\n}\n\nint main() {\n    char str[200];\n    printf("Enter a sentence: ");\n    fgets(str, 200, stdin);\n    printf("Word count: %d\\n", countWords(str));\n    return 0;\n}' },
      { day: 22, title: 'Structures', topics: ['struct keyword', 'Structure declaration', 'Accessing members'], subtopics: ['Data modeling', 'Record systems', 'Nested structures', 'typedef'], exercises: ['Student record (name, roll, marks)', 'Point structure (x, y)', 'Date structure', 'Employee record'], goal: 'Model real-world data.', starterCode: '#include <stdio.h>\n\ntypedef struct {\n    char name[50];\n    int roll;\n    float marks;\n} Student;\n\nint main() {\n    Student s;\n    printf("Name: "); scanf("%s", s.name);\n    printf("Roll: "); scanf("%d", &s.roll);\n    printf("Marks: "); scanf("%f", &s.marks);\n\n    printf("\\n--- Student Info ---\\n");\n    printf("Name: %s\\nRoll: %d\\nMarks: %.1f\\n", s.name, s.roll, s.marks);\n    return 0;\n}' },
      { day: 23, title: 'Array of Structures', topics: ['Managing multiple records', 'Sorting structures', 'Searching in structures'], subtopics: ['Database-like operations', 'Record comparison', 'Structure arrays', 'Menu-driven record system'], exercises: ['Store and display 5 students', 'Sort students by marks', 'Search student by roll number', 'Find topper from records'], goal: 'Manage structured data collections.', starterCode: '#include <stdio.h>\n\ntypedef struct {\n    char name[30];\n    int roll;\n    float marks;\n} Student;\n\nint main() {\n    int n = 3;\n    Student s[3];\n\n    for (int i = 0; i < n; i++) {\n        printf("Student %d - Name Roll Marks: ", i+1);\n        scanf("%s %d %f", s[i].name, &s[i].roll, &s[i].marks);\n    }\n\n    // Find topper\n    int top = 0;\n    for (int i = 1; i < n; i++)\n        if (s[i].marks > s[top].marks) top = i;\n\n    printf("\\nTopper: %s (%.1f marks)\\n", s[top].name, s[top].marks);\n    return 0;\n}' },
      { day: 24, title: 'File Handling', topics: ['fopen, fclose', 'fprintf, fscanf', 'fgets, fputs'], subtopics: ['File modes (r, w, a)', 'Error handling in file ops', 'Data persistence concept', 'Reading line by line'], exercises: ['Write data to a file', 'Read and display file contents', 'Append data to existing file', 'Copy contents of one file to another'], goal: 'Understand data persistence.', starterCode: '#include <stdio.h>\n\nint main() {\n    FILE *fp;\n    \n    // Write to file\n    fp = fopen("output.txt", "w");\n    if (fp == NULL) { printf("Error!\\n"); return 1; }\n    fprintf(fp, "Hello from C!\\n");\n    fprintf(fp, "File handling complete.\\n");\n    fclose(fp);\n    \n    // Read from file\n    char line[100];\n    fp = fopen("output.txt", "r");\n    printf("File contents:\\n");\n    while (fgets(line, 100, fp) != NULL)\n        printf("%s", line);\n    fclose(fp);\n    \n    return 0;\n}' },
      { day: 25, title: 'Mini Project 1', topics: ['Student Record System', 'CRUD operations', 'File-based storage'], subtopics: ['Menu-driven design', 'Data validation', 'Error handling', 'Code organization'], exercises: ['Build complete Student Record System with Add/View/Search/Delete/Save to file functionality'], goal: 'Build a complete real-world project.', starterCode: '#include <stdio.h>\n#include <string.h>\n\ntypedef struct {\n    int roll;\n    char name[50];\n    float marks;\n} Student;\n\nStudent records[100];\nint count = 0;\n\nvoid addStudent() {\n    printf("Roll: "); scanf("%d", &records[count].roll);\n    printf("Name: "); scanf("%s", records[count].name);\n    printf("Marks: "); scanf("%f", &records[count].marks);\n    count++;\n    printf("Student added!\\n");\n}\n\nvoid viewAll() {\n    printf("\\n%-5s %-20s %s\\n", "Roll", "Name", "Marks");\n    for (int i = 0; i < count; i++)\n        printf("%-5d %-20s %.1f\\n", records[i].roll, records[i].name, records[i].marks);\n}\n\nint main() {\n    int ch;\n    do {\n        printf("\\n1.Add 2.View 3.Exit: ");\n        scanf("%d", &ch);\n        switch(ch) {\n            case 1: addStudent(); break;\n            case 2: viewAll(); break;\n        }\n    } while(ch != 3);\n    return 0;\n}' },
    ],
  },
  {
    id: 4,
    name: 'Memory & System Control',
    tagline: 'Now we move to serious level. Pointers, DMA, and bitwise.',
    color: '#ef4444',
    gradient: 'from-[#ef4444] to-[#dc2626]',
    icon: 'Cpu',
    dayRange: [26, 35],
    days: [
      { day: 26, title: 'Pointers Deep Introduction', topics: ['Address operator &', 'Pointer declaration *', 'Dereferencing'], subtopics: ['Memory visualization', 'Pointer size', 'NULL pointer', 'Pointer types'], exercises: ['Print address of variables', 'Access value through pointer', 'Swap two numbers using pointers', 'Pointer arithmetic basics'], goal: 'Understand memory addresses.', starterCode: '#include <stdio.h>\n\nint main() {\n    int x = 42;\n    int *ptr = &x;\n\n    printf("Value of x: %d\\n", x);\n    printf("Address of x: %p\\n", (void*)&x);\n    printf("ptr points to: %p\\n", (void*)ptr);\n    printf("Value via ptr: %d\\n", *ptr);\n\n    *ptr = 100;\n    printf("x after *ptr=100: %d\\n", x);\n    return 0;\n}' },
      { day: 27, title: 'Pointer Arithmetic', topics: ['Pointer increment/decrement', 'Pointer and arrays', 'Memory traversal'], subtopics: ['Pointer offset', 'Array name as pointer', 'Pointer subtraction', 'void pointers intro'], exercises: ['Traverse array using pointers', 'Reverse array using pointers', 'Find sum using pointer traversal', 'Pointer comparison'], goal: 'Navigate memory like a pro.', starterCode: '#include <stdio.h>\n\nint main() {\n    int arr[] = {10, 20, 30, 40, 50};\n    int *ptr = arr;\n\n    printf("Array via pointers:\\n");\n    for (int i = 0; i < 5; i++) {\n        printf("arr[%d] = %d (addr: %p)\\n", i, *(ptr+i), (void*)(ptr+i));\n    }\n    return 0;\n}' },
      { day: 28, title: 'Pointers & Arrays', topics: ['Array-pointer equivalence', 'Passing arrays to functions', 'Pointer to array'], subtopics: ['Array decay', 'Const pointers', 'Array of pointers', '2D arrays with pointers'], exercises: ['Sort array using pointer-based function', 'String operations using pointers', 'Find max using pointer function', 'Matrix with pointers'], goal: 'Deep connection between pointers and arrays.', starterCode: '#include <stdio.h>\n\nvoid printArray(int *arr, int n) {\n    for (int i = 0; i < n; i++)\n        printf("%d ", *(arr + i));\n    printf("\\n");\n}\n\nint findMax(int *arr, int n) {\n    int max = *arr;\n    for (int i = 1; i < n; i++)\n        if (*(arr+i) > max) max = *(arr+i);\n    return max;\n}\n\nint main() {\n    int arr[] = {23, 55, 12, 89, 34};\n    printArray(arr, 5);\n    printf("Max: %d\\n", findMax(arr, 5));\n    return 0;\n}' },
      { day: 29, title: 'Pointers & Functions', topics: ['Call by reference', 'Pointer as function parameter', 'Returning pointers'], subtopics: ['Modifying caller variables', 'Multiple return values', 'Dangling pointers', 'Function pointers intro'], exercises: ['Swap using pointers', 'Return multiple values from function', 'Sort using pointer parameters', 'Calculator with function pointers'], goal: 'Deep control over function data flow.', starterCode: '#include <stdio.h>\n\nvoid swap(int *a, int *b) {\n    int temp = *a;\n    *a = *b;\n    *b = temp;\n}\n\nvoid minMax(int arr[], int n, int *min, int *max) {\n    *min = *max = arr[0];\n    for (int i = 1; i < n; i++) {\n        if (arr[i] < *min) *min = arr[i];\n        if (arr[i] > *max) *max = arr[i];\n    }\n}\n\nint main() {\n    int a = 5, b = 10;\n    swap(&a, &b);\n    printf("After swap: a=%d, b=%d\\n", a, b);\n\n    int arr[] = {3, 7, 1, 9, 4};\n    int min, max;\n    minMax(arr, 5, &min, &max);\n    printf("Min=%d, Max=%d\\n", min, max);\n    return 0;\n}' },
      { day: 30, title: 'Dynamic Memory', topics: ['malloc()', 'calloc()', 'free()', 'realloc()'], subtopics: ['Heap vs Stack', 'Memory leaks', 'Dynamic arrays', 'Memory debugging'], exercises: ['Dynamic array creation', 'Dynamic string input', 'Resize array with realloc', 'Dynamic 2D array'], goal: 'Control memory allocation.', starterCode: '#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int n;\n    printf("How many numbers? ");\n    scanf("%d", &n);\n\n    int *arr = (int *)malloc(n * sizeof(int));\n    if (!arr) { printf("Memory error!\\n"); return 1; }\n\n    printf("Enter %d numbers:\\n", n);\n    for (int i = 0; i < n; i++)\n        scanf("%d", &arr[i]);\n\n    int sum = 0;\n    for (int i = 0; i < n; i++) sum += arr[i];\n    printf("Sum = %d\\n", sum);\n\n    free(arr);\n    return 0;\n}' },
      { day: 31, title: 'Advanced Memory Logic', topics: ['Dynamic structures', 'Linked list concept', 'Memory management patterns'], subtopics: ['Dynamic array of structures', 'Memory pool concept', 'Fragmentation awareness', 'Best practices'], exercises: ['Dynamic student records', 'Simple linked list (insert + display)', 'Memory-efficient string storage', 'Dynamic matrix operations'], goal: 'Advanced memory management.', starterCode: '#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct Node {\n    int data;\n    struct Node *next;\n} Node;\n\nNode* createNode(int val) {\n    Node *n = (Node*)malloc(sizeof(Node));\n    n->data = val;\n    n->next = NULL;\n    return n;\n}\n\nvoid printList(Node *head) {\n    while (head) {\n        printf("%d -> ", head->data);\n        head = head->next;\n    }\n    printf("NULL\\n");\n}\n\nint main() {\n    Node *head = createNode(10);\n    head->next = createNode(20);\n    head->next->next = createNode(30);\n    printList(head);\n    return 0;\n}' },
      { day: 32, title: 'Bitwise Logic', topics: ['AND &, OR |, XOR ^', 'Left/Right shift', 'NOT ~'], subtopics: ['Bit manipulation tricks', 'Setting/clearing bits', 'Checking bit status', 'Power of 2 check'], exercises: ['Check if number is power of 2', 'Count set bits', 'Swap without temp variable', 'Toggle specific bit'], goal: 'Think at the bit level.', starterCode: '#include <stdio.h>\n\nint countSetBits(int n) {\n    int count = 0;\n    while (n) { count += n & 1; n >>= 1; }\n    return count;\n}\n\nint isPowerOf2(int n) {\n    return n > 0 && (n & (n-1)) == 0;\n}\n\nint main() {\n    int n = 12;\n    printf("Set bits in %d: %d\\n", n, countSetBits(n));\n    printf("16 is power of 2: %s\\n", isPowerOf2(16) ? "Yes" : "No");\n    printf("XOR swap: ");\n    int a=5, b=9;\n    a ^= b; b ^= a; a ^= b;\n    printf("a=%d, b=%d\\n", a, b);\n    return 0;\n}' },
      { day: 33, title: 'Preprocessor & Compilation', topics: ['#define macros', '#include system', 'Conditional compilation (#ifdef)'], subtopics: ['How compilation works', 'Preprocessing stage', 'Macro vs function', 'Include guards'], exercises: ['Create useful macros (MAX, MIN, SQUARE)', 'Conditional debug logging', 'Header file creation', 'Multi-file basics'], goal: 'Understand the build process.', starterCode: '#include <stdio.h>\n\n#define MAX(a,b) ((a) > (b) ? (a) : (b))\n#define MIN(a,b) ((a) < (b) ? (a) : (b))\n#define SQUARE(x) ((x) * (x))\n#define PI 3.14159\n\n#define DEBUG 1\n\nint main() {\n    printf("MAX(5,3) = %d\\n", MAX(5,3));\n    printf("SQUARE(4) = %d\\n", SQUARE(4));\n    printf("Circle area (r=5): %.2f\\n", PI * SQUARE(5));\n\n    #if DEBUG\n    printf("[DEBUG] Program running in debug mode\\n");\n    #endif\n\n    return 0;\n}' },
      { day: 34, title: 'Makefile & Multi-file Projects', topics: ['Header files (.h)', 'Multiple .c files', 'Compilation automation'], subtopics: ['Separate compilation', 'Linking concept', 'extern keyword', 'Static functions'], exercises: ['Split project into header + source files', 'Create a simple Makefile', 'Multi-file calculator project', 'Library concept (static)'], goal: 'Build professional multi-file projects.', starterCode: '// main.c - Multi-file project example\n#include <stdio.h>\n\n// In a real project these would be in separate files\n// math_utils.h / math_utils.c\n\nint add(int a, int b) { return a + b; }\nint multiply(int a, int b) { return a * b; }\nint factorial(int n) {\n    if (n <= 1) return 1;\n    return n * factorial(n-1);\n}\n\nint main() {\n    printf("add(3,4) = %d\\n", add(3,4));\n    printf("multiply(5,6) = %d\\n", multiply(5,6));\n    printf("factorial(5) = %d\\n", factorial(5));\n    printf("\\nIn real projects, each function\\n");\n    printf("would be in separate .c files!\\n");\n    return 0;\n}' },
      { day: 35, title: 'Mini Project 2', topics: ['Multi-module project', 'File I/O integration', 'Complete system design'], subtopics: ['Error handling everywhere', 'User experience design', 'Data validation', 'Code review thinking'], exercises: ['Build a Contact Management System with file storage, search, edit, delete features, organized in modular functions'], goal: 'Build a production-quality C project.', starterCode: '#include <stdio.h>\n#include <string.h>\n\ntypedef struct {\n    char name[50];\n    char phone[15];\n    char email[50];\n} Contact;\n\nContact contacts[100];\nint count = 0;\n\nvoid addContact() {\n    printf("Name: "); scanf("%s", contacts[count].name);\n    printf("Phone: "); scanf("%s", contacts[count].phone);\n    printf("Email: "); scanf("%s", contacts[count].email);\n    count++;\n    printf("Contact added!\\n");\n}\n\nvoid searchContact() {\n    char query[50];\n    printf("Search name: "); scanf("%s", query);\n    for (int i = 0; i < count; i++)\n        if (strstr(contacts[i].name, query))\n            printf("%s | %s | %s\\n", contacts[i].name, contacts[i].phone, contacts[i].email);\n}\n\nint main() {\n    int ch;\n    do {\n        printf("\\n1.Add 2.Search 3.Exit: ");\n        scanf("%d", &ch);\n        if (ch == 1) addContact();\n        if (ch == 2) searchContact();\n    } while(ch != 3);\n    return 0;\n}' },
    ],
  },
  {
    id: 5,
    name: 'Company-Level Thinking',
    tagline: 'Simulate interview style. Think like a professional programmer.',
    color: '#a855f7',
    gradient: 'from-[#a855f7] to-[#7c3aed]',
    icon: 'Trophy',
    dayRange: [36, 40],
    days: [
      { day: 36, title: 'Time & Space Complexity', topics: ['Big-O notation', 'O(1), O(n), O(n²), O(log n)', 'Space complexity basics'], subtopics: ['Comparing algorithms', 'Best/worst/average case', 'Amortized analysis intro', 'Practical optimization'], exercises: ['Analyze complexity of your past code', 'Compare linear vs binary search', 'Optimize nested loop problem', 'Space-efficient solutions'], goal: 'Think about efficiency.', starterCode: '#include <stdio.h>\n#include <time.h>\n\n// O(n) - Linear Search\nint linearSearch(int arr[], int n, int target) {\n    for (int i = 0; i < n; i++)\n        if (arr[i] == target) return i;\n    return -1;\n}\n\n// O(log n) - Binary Search\nint binarySearch(int arr[], int n, int target) {\n    int lo = 0, hi = n-1;\n    while (lo <= hi) {\n        int mid = (lo+hi)/2;\n        if (arr[mid] == target) return mid;\n        else if (arr[mid] < target) lo = mid+1;\n        else hi = mid-1;\n    }\n    return -1;\n}\n\nint main() {\n    int arr[1000];\n    for (int i = 0; i < 1000; i++) arr[i] = i*2;\n    \n    printf("Linear: found at %d\\n", linearSearch(arr, 1000, 500));\n    printf("Binary: found at %d\\n", binarySearch(arr, 1000, 500));\n    return 0;\n}' },
      { day: 37, title: 'Edge Case Analysis', topics: ['Boundary conditions', 'Invalid inputs', 'Extreme values'], subtopics: ['Empty input handling', 'Overflow detection', 'Negative numbers', 'Special characters'], exercises: ['Handle empty array gracefully', 'Integer overflow detection', 'Validate all user inputs', 'Boundary testing for sorting'], goal: 'Think about edge cases like a pro.', starterCode: '#include <stdio.h>\n#include <limits.h>\n\n// Safe addition with overflow check\nint safeAdd(int a, int b, int *result) {\n    if ((b > 0 && a > INT_MAX - b) ||\n        (b < 0 && a < INT_MIN - b)) {\n        return 0; // overflow!\n    }\n    *result = a + b;\n    return 1; // success\n}\n\nint main() {\n    int result;\n    if (safeAdd(INT_MAX, 1, &result))\n        printf("Result: %d\\n", result);\n    else\n        printf("Overflow detected!\\n");\n\n    if (safeAdd(100, 200, &result))\n        printf("100 + 200 = %d\\n", result);\n    return 0;\n}' },
      { day: 38, title: 'Company-style Problems', topics: ['Array-heavy logic problems', 'String manipulation challenges', 'Memory-efficient solutions'], subtopics: ['Two-pointer technique', 'Sliding window concept', 'Hash-like approach in C', 'Interview patterns'], exercises: ['Two Sum problem', 'Move zeroes to end', 'Rotate array by K', 'Find duplicate in array'], goal: 'Solve interview-level problems.', starterCode: '#include <stdio.h>\n\nvoid moveZeroes(int arr[], int n) {\n    int j = 0;\n    for (int i = 0; i < n; i++)\n        if (arr[i] != 0)\n            arr[j++] = arr[i];\n    while (j < n) arr[j++] = 0;\n}\n\nvoid rotateRight(int arr[], int n, int k) {\n    k %= n;\n    // Reverse all, reverse first k, reverse rest\n    for (int l=0,r=n-1; l<r; l++,r--) { int t=arr[l]; arr[l]=arr[r]; arr[r]=t; }\n    for (int l=0,r=k-1; l<r; l++,r--) { int t=arr[l]; arr[l]=arr[r]; arr[r]=t; }\n    for (int l=k,r=n-1; l<r; l++,r--) { int t=arr[l]; arr[l]=arr[r]; arr[r]=t; }\n}\n\nint main() {\n    int arr[] = {0, 1, 0, 3, 12};\n    moveZeroes(arr, 5);\n    printf("After moveZeroes: ");\n    for (int i = 0; i < 5; i++) printf("%d ", arr[i]);\n    printf("\\n");\n    return 0;\n}' },
      { day: 39, title: 'System Design in C', topics: ['Mini Banking System', 'File-based login system', 'Complete system architecture'], subtopics: ['Session management', 'Data encryption basics', 'Error logging', 'System modularity'], exercises: ['Build a mini banking system with login, deposit, withdraw, balance check, and transaction history stored in files'], goal: 'Design complete systems in C.', starterCode: '#include <stdio.h>\n#include <string.h>\n\ntypedef struct {\n    int accNo;\n    char name[50];\n    char pin[5];\n    float balance;\n} Account;\n\nAccount acc = {1001, "Ishu Kumar", "1234", 5000.00};\n\nint login() {\n    char pin[5];\n    printf("Enter PIN: "); scanf("%s", pin);\n    return strcmp(pin, acc.pin) == 0;\n}\n\nvoid deposit() {\n    float amt;\n    printf("Amount: "); scanf("%f", &amt);\n    acc.balance += amt;\n    printf("New balance: %.2f\\n", acc.balance);\n}\n\nvoid withdraw() {\n    float amt;\n    printf("Amount: "); scanf("%f", &amt);\n    if (amt > acc.balance) printf("Insufficient funds!\\n");\n    else { acc.balance -= amt; printf("New balance: %.2f\\n", acc.balance); }\n}\n\nint main() {\n    if (!login()) { printf("Wrong PIN!\\n"); return 1; }\n    printf("Welcome, %s!\\n", acc.name);\n    int ch;\n    do {\n        printf("\\n1.Deposit 2.Withdraw 3.Balance 4.Exit: ");\n        scanf("%d", &ch);\n        if (ch==1) deposit();\n        if (ch==2) withdraw();\n        if (ch==3) printf("Balance: %.2f\\n", acc.balance);\n    } while(ch != 4);\n    return 0;\n}' },
      { day: 40, title: 'Mastery Assessment', topics: ['15 graded problems', '1 complete project', 'Code review thinking'], subtopics: ['Self-evaluation', 'Code quality assessment', 'Documentation practice', 'Next steps planning'], exercises: ['Complete mastery test with 15 problems covering all 40 days of concepts, plus build a complete Library Management System'], goal: 'Prove your C mastery.', starterCode: '#include <stdio.h>\n#include <string.h>\n\n// MASTERY PROJECT: Library Management System\ntypedef struct {\n    int id;\n    char title[100];\n    char author[50];\n    int available;\n} Book;\n\nBook library[50];\nint bookCount = 0;\n\nvoid addBook() {\n    Book *b = &library[bookCount];\n    b->id = bookCount + 1;\n    printf("Title: "); scanf(" %[^\\n]", b->title);\n    printf("Author: "); scanf(" %[^\\n]", b->author);\n    b->available = 1;\n    bookCount++;\n    printf("Book added (ID: %d)\\n", b->id);\n}\n\nvoid listBooks() {\n    printf("\\n%-4s %-30s %-20s %s\\n", "ID", "Title", "Author", "Status");\n    for (int i = 0; i < bookCount; i++)\n        printf("%-4d %-30s %-20s %s\\n", library[i].id, library[i].title,\n               library[i].author, library[i].available ? "Available" : "Issued");\n}\n\nint main() {\n    int ch;\n    printf("=== Library Management System ===\\n");\n    do {\n        printf("\\n1.Add 2.List 3.Exit: ");\n        scanf("%d", &ch);\n        if (ch==1) addBook();\n        if (ch==2) listBooks();\n    } while(ch != 3);\n    printf("Congratulations! You completed 40 days!\\n");\n    return 0;\n}' },
    ],
  },
];
